version: '3.7'

services:
  postgres:
    image: postgres:14-alpine
    restart: always
    volumes:
      - pg-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: crashmax
    ports:
      - 5432:5432

volumes:
  pg-data:
